openapi: 3.0.2
info:
  title: sample API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /books:
    get:
      operationId: getBooks
      responses:
        '200':
          description: 書籍一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookProperties'
    post:
      operationId: createBook
      responses:
        '200':
          description: 作成された書籍
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
components:
  schemas:
    BookProperties:
      type: object
      required:
      - name
      - author
      properties:
        name:
          type: string
          example: "The Raging Tide: Or, the Black Doll's Imbroglio"
        author:
          type: string
          example: Edward Gorey
    Book:
      type: object
      properties:
        book:
          $ref: '#/components/schemas/BookProperties'