openapi: 3.0.2
info:
  title: sample API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /books:
    get:
      operationId: getBooks
      responses:
        '200':
          description: 書籍一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookProperties'
    post:
      operationId: createBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: 作成された書籍
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
components:
  schemas:
    BookProperties:
      $ref: './components/book_properties.yml'
    Book:
      type: object
      properties:
        book:
          $ref: '#/components/schemas/BookProperties'